const fs = require('fs');
const c = [];
c.push('"use client";');
c.push('import { useState, useEffect } from "react";');
c.push('import { supabaseBrowser } from "@/lib/supabase";');
c.push('import Link from "next/link";');
c.push('');
c.push('const STATUS_COLORS = {');
c.push('  pending:   { bg: "#FEF3C7", color: "#92400E" },');
c.push('  active:    { bg: "#D1FAE5", color: "#065F46" },');
c.push('  cancelled: { bg: "#FEE2E2", color: "#991B1B" },');
c.push('}');
c.push('');
c.push('export default function OrdersPage() {');
c.push('  const [orders, setOrders]     = useState([]);');
c.push('  const [loading, setLoading]   = useState(true);');
c.push('  const [expanded, setExpanded] = useState(null);');
c.push('  const [msg, setMsg]           = useState("");');
c.push('');
c.push('  useEffect(() => { load(); }, []);');
c.push('');
c.push('  async function load() {');
c.push('    setLoading(true);');
c.push('    const { data, error } = await supabaseBrowser');
c.push('      .from("orders").select("*").order("created_at", { ascending: false });');
c.push('    if (error) console.error(error);');
c.push('    setOrders(data || []);');
c.push('    setLoading(false);');
c.push('  }');
c.push('');
c.push('  async function updateStatus(id, status) {');
c.push('    await supabaseBrowser.from("orders").update({ status }).eq("id", id);');
c.push('    setMsg("Updated!"); setTimeout(() => setMsg(""), 2000); load();');
c.push('  }');
c.push('');
c.push('  async function deleteOrder(id) {');
c.push('    if (!confirm("Delete this order?")) return;');
c.push('    await supabaseBrowser.from("orders").delete().eq("id", id);');
c.push('    load();');
c.push('  }');
c.push('');
c.push('  function fmt(dateStr) {');
c.push('    if (!dateStr) return "";');
c.push('    return new Date(dateStr).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });');
c.push('  }');
c.push('');
c.push('  return (');
c.push('    <div style={{ minHeight: "100vh", background: "#f8f7f4", padding: "40px 24px" }}>');
c.push('      <div style={{ maxWidth: 1200, margin: "0 auto" }}>');
c.push('        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 32 }}>');
c.push('          <h1 style={{ fontFamily: "serif", fontSize: 28, fontWeight: 900, color: "#0F172A", letterSpacing: -1 }}>📋 Orders</h1>');
c.push('          <div style={{ display: "flex", gap: 10, alignItems: "center" }}>');
c.push('            {msg && <span style={{ fontSize: 13, color: "#10B981", fontWeight: 600 }}>{msg}</span>}');
c.push('            <button onClick={load} style={{ padding: "8px 16px", background: "#f1f5f9", border: "none", borderRadius: 8, fontSize: 12, cursor: "pointer" }}>Refresh</button>');
c.push('            <Link href="/admin" style={{ padding: "8px 18px", background: "#0F172A", color: "white", borderRadius: 8, fontSize: 13, fontWeight: 600, textDecoration: "none" }}>← Back</Link>');
c.push('          </div>');
c.push('        </div>');
c.push('        <div style={{ background: "white", borderRadius: 16, border: "1px solid #e2e8f0", overflow: "hidden" }}>');
c.push('          {loading ? (');
c.push('            <div style={{ padding: 40, textAlign: "center", color: "#94a3b8" }}>Loading...</div>');
c.push('          ) : orders.length === 0 ? (');
c.push('            <div style={{ padding: 40, textAlign: "center", color: "#94a3b8" }}>No orders yet.</div>');
c.push('          ) : (');
c.push('            <table style={{ width: "100%", borderCollapse: "collapse" }}>');
c.push('              <thead>');
c.push('                <tr style={{ background: "#f8f7f4", borderBottom: "2px solid #e2e8f0" }}>');
c.push('                  {["Date","Name","Email","Domain","Plan","Designs","Extra Domain","Total","Status",""].map(h => (');
c.push('                    <th key={h} style={{ padding: "12px 16px", textAlign: "left", fontSize: 11, fontWeight: 700, color: "#64748b", textTransform: "uppercase", letterSpacing: 0.8, whiteSpace: "nowrap" }}>{h}</th>');
c.push('                  ))}');
c.push('                </tr>');
c.push('              </thead>');
c.push('              <tbody>');
c.push('                {orders.map((o, i) => {');
c.push('                  const sc = STATUS_COLORS[o.status] || STATUS_COLORS.pending;');
c.push('                  const designs = Array.isArray(o.selected_designs) ? o.selected_designs.filter(Boolean) : [];');
c.push('                  const extraDomains = Array.isArray(o.addon_domain_list) ? o.addon_domain_list.filter(Boolean) : [];');
c.push('                  const isExp = expanded === o.id;');
c.push('                  return (');
c.push('                    <>');
c.push('                      <tr key={o.id} style={{ borderBottom: "1px solid #f1f5f9", background: i % 2 === 0 ? "white" : "#fafafa", cursor: "pointer" }} onClick={() => setExpanded(isExp ? null : o.id)}>');
c.push('                        <td style={{ padding: "14px 16px", fontSize: 12, color: "#64748b", whiteSpace: "nowrap" }}>{fmt(o.created_at)}</td>');
c.push('                        <td style={{ padding: "14px 16px", fontSize: 13, fontWeight: 600, color: "#0F172A", whiteSpace: "nowrap" }}>{o.name}</td>');
c.push('                        <td style={{ padding: "14px 16px", fontSize: 12, color: "#64748b" }}>{o.email}</td>');
c.push('                        <td style={{ padding: "14px 16px", fontSize: 12, fontFamily: "monospace", color: "#0F172A" }}>{o.domain}</td>');
c.push('                        <td style={{ padding: "14px 16px", fontSize: 12, fontWeight: 600, color: "#0F172A" }}>{o.plan}</td>');
c.push('                        <td style={{ padding: "14px 16px", fontSize: 12 }}>');
c.push('                          {designs.length > 0 ? designs.map((d,i) => (');
c.push('                            <span key={i} style={{ display:"inline-block", padding:"2px 8px", background: i===0 ? "#f1f5f9" : "#FEF3C7", borderRadius:20, fontSize:11, marginRight:4, color: i===0 ? "#0F172A" : "#92400E", fontWeight:600 }}>{d}</span>');
c.push('                          )) : <span style={{ color:"#94a3b8" }}>—</span>}');
c.push('                        </td>');
c.push('                        <td style={{ padding: "14px 16px", fontSize: 12, color: extraDomains.length ? "#F59E0B" : "#94a3b8", fontFamily:"monospace" }}>');
c.push('                          {extraDomains.length ? extraDomains.join(", ") : "—"}');
c.push('                        </td>');
c.push('                        <td style={{ padding: "14px 16px", fontSize: 13, fontWeight: 700, color: "#0F172A", whiteSpace: "nowrap" }}></td>');
c.push('                        <td style={{ padding: "14px 16px" }} onClick={e => e.stopPropagation()}>');
c.push('                          <select value={o.status || "pending"} onChange={e => updateStatus(o.id, e.target.value)}');
c.push('                            style={{ padding: "4px 8px", borderRadius: 20, border: "none", fontSize: 11, fontWeight: 700, background: sc.bg, color: sc.color, cursor: "pointer" }}>');
c.push('                            <option value="pending">Pending</option>');
c.push('                            <option value="active">Active</option>');
c.push('                            <option value="cancelled">Cancelled</option>');
c.push('                          </select>');
c.push('                        </td>');
c.push('                        <td style={{ padding: "14px 16px" }} onClick={e => e.stopPropagation()}>');
c.push('                          <button onClick={() => deleteOrder(o.id)} style={{ padding: "5px 10px", background: "#fff5f5", color: "#dc2626", border: "1px solid #fee2e2", borderRadius: 6, fontSize: 11, cursor: "pointer" }}>🗑</button>');
c.push('                        </td>');
c.push('                      </tr>');
c.push('                      {isExp && (');
c.push('                        <tr key={o.id + "-exp"} style={{ background: "#FFFBEB", borderBottom: "1px solid #FDE68A" }}>');
c.push('                          <td colSpan={10} style={{ padding: "16px 24px" }}>');
c.push('                            <div style={{ display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:16, fontSize:13 }}>');
c.push('                              <div><div style={{ fontWeight:700, color:"#92400E", marginBottom:4 }}>Designs</div><div style={{ color:"#78350F" }}>{designs.length ? designs.join(", ") : "—"}</div></div>');
c.push('                              <div><div style={{ fontWeight:700, color:"#92400E", marginBottom:4 }}>Extra Domain</div><div style={{ color:"#78350F", fontFamily:"monospace" }}>{extraDomains.length ? extraDomains.join(", ") : "—"}</div></div>');
c.push('                              <div><div style={{ fontWeight:700, color:"#92400E", marginBottom:4 }}>Notes</div><div style={{ color:"#78350F" }}>{o.notes || "—"}</div></div>');
c.push('                              <div><div style={{ fontWeight:700, color:"#92400E", marginBottom:4 }}>Breakdown</div><div style={{ color:"#78350F" }}>Plan: {o.addon_domain ? " +  domain" : ""}{o.addon_design_count > 0 ? " + $" + (o.addon_design_count*20) + " designs" : ""}</div></div>');
c.push('                            </div>');
c.push('                          </td>');
c.push('                        </tr>');
c.push('                      )}');
c.push('                    </>');
c.push('                  );');
c.push('                })}');
c.push('              </tbody>');
c.push('            </table>');
c.push('          )}');
c.push('        </div>');
c.push('        <div style={{ marginTop: 16, fontSize: 12, color: "#94a3b8" }}>');
c.push('          {orders.length} order{orders.length !== 1 ? "s" : ""} total ·  revenue');
c.push('        </div>');
c.push('      </div>');
c.push('    </div>');
c.push('  );');
c.push('}');
fs.writeFileSync('app/admin/orders/page.jsx', c.join('\n'), 'utf8');
console.log('done');
